<template>
  <masterLayout>
    <div class="center_div voucher_container margin-top-center-div">
      <div class="pad_div">
        <div class="mt-3 tabs__lists">
          <h5>VOUCHER MONITOR</h5>
        </div>
      </div>
      <div class="form_content">
        <form>
          <div class="form-group row">
            <label for="amount" class="col-sm-4 col-form-label"
              >VOUCHER PIN TO VERIFY</label
            >
            <div class="col-sm-8">
              <input
                type="number"
                class="form-control form__input"
                placeholder="e.g. 1234567890"
                v-model="voucherPin"
              />
              <div class="mt-4 mx-auto text-center">
                <button
                  class="btn btn_theme"
                  @click="verifyVoucher($event)"
                  :disabled="isButtonDisabled ? true : null"
                  :style="[
                    isButtonDisabled
                      ? { cursor: 'not-allowed' }
                      : { cursor: 'pointer' },
                  ]"
                >
                  Verify Voucher
                  <img
                    src="@/assets/img/git_loader.gif"
                    style="display: none"
                    width="15px"
                    class="ml-3 loader"
                  />
                </button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
    
    <div class="full__row_section p-5 mt-3 center_div margin-top-center-div ep_card mb-5" v-if="voucherVerified">
        <div class="">
                <div class="row align-items-center mt-3">
                  <div class="col-md-4">
                    <label> Pin</label>
                  </div>
                  <div class="col-md-8">
                    <div class="input__block">
                      <input
                        type="text"
                        readonly
                        v-model="voucherDetails.pin"
                      />
                    </div>
                  </div>
                </div>
                <div class="row align-items-center mt-3">
                  <div class="col-md-4">
                    <label>Voucher Amount</label>
                  </div>
                  <div class="col-md-8">
                    <div class="input__block">
                      <input
                        type="text"
                        class=""
                        readonly
                        v-model="voucherDetails.amount"
                      />
                    </div>
                  </div>
                </div>
                <div class="row align-items-center mt-3" v-if="usedVoucher && !unUsed">
                  <div class="col-md-4">
                    <label>Amount Spent</label>
                  </div>
                  <div class="col-md-8">
                    <div class="input__block">
                      <input
                        type="text"
                        class=""
                        readonly
                        v-model="voucherDetails.amountSpent"
                      />
                    </div>
                  </div>
                </div>
                <div class="row align-items-center mt-3">
                  <div class="col-md-4">
                    <label>Generated By</label>
                  </div>
                  <div class="col-md-8">
                    <div class="input__block">
                      <input
                        type="text"
                        class=""
                        readonly
                        v-model="voucherDetails.userId"
                      />
                    </div>
                  </div>
                </div>
                <div class="row align-items-center mt-3">
                  <div class="col-md-4">
                    <label>Date Generated</label>
                  </div>
                  <div class="col-md-8">
                    <div class="input__block">
                      <input
                        type="text"
                        class=""
                        readonly
                        v-model="voucherDetails.dateGenerated"
                      />
                    </div>
                  </div>
                </div>
                <div class="row align-items-center mt-3" v-if="showExpiry">
                  <div class="col-md-4">
                    <label>Expiry Date</label>
                  </div>
                  <div class="col-md-8">
                    <div class="input__block">
                      <input
                        type="text"
                        class=""
                        readonly
                        v-model="voucherDetails.expiry"
                      />
                    </div>
                  </div>
                </div>
                <div class="row align-items-center mt-3">
                  <div class="col-md-4">
                    <label>Deleted</label>
                  </div>
                  <div class="col-md-8">
                    <div class="input__block">
                      <input
                        type="text"
                        class=""
                        readonly
                        v-model="voucherDetails.deleted"
                      />
                    </div>
                  </div>
                </div>              
                <div class="row align-items-center mt-3">
                  <div class="col-md-4">
                    <label>Used</label>
                  </div>
                  <div class="col-md-8">
                    <div class="input__block">
                      <input
                        type="text"
                        class=""
                        readonly
                        v-model="voucherDetails.isUsed"
                      />
                    </div>
                  </div>
                </div>
                <div class="row align-items-center mt-3" v-if="usedVoucher">
                  <div class="col-md-4">
                    <label>Station</label>
                  </div>
                  <div class="col-md-8">
                    <div class="input__block">
                      <input
                        type="text"
                        class=""
                        readonly
                        v-model="voucherDetails.branchName"
                      />
                    </div>
                  </div>
                </div>
                <div class="row align-items-center mt-3" v-if="usedVoucher && !unUsed">
                  <div class="col-md-4">
                    <label>Transaction Date</label>
                  </div>
                  <div class="col-md-8">
                    <div class="input__block">
                      <input
                        type="text"
                        class=""
                        readonly
                        v-model="voucherDetails.transactionDate"
                      />
                    </div>
                  </div>
                </div>
                <div class="mt-3" v-show="showExtras">
                    <div class="text-center mt-3">
                      <router-link :to="{name: 'extendVoucher'}" class="btn btn-success mr-2">Extend Voucher<i class="fa fa-angle-right ml-2" aria-hidden="true"></i></router-link>                     
                      <button class="btn btn-primary mr-2" @click="cancelVoucher"
                        :disabled="isButtonDisabled ? true : null"
                        :style="[
                          isButtonDisabled
                            ? { cursor: 'not-allowed' }
                            : { cursor: 'pointer' }
                        ]"
                      ><i class="fa fa-repeat mr-1" aria-hidden="true"></i>Return to Wallet
                        <img
                          src="@/assets/img/git_loader.gif"
                          style="display:none"
                          width="25px"
                          class="ml-3 loader"
                        />
                      </button>
                      <button class="btn btn-info" @click="expireVoucher"
                        :disabled="isButtonDisabled2 ? true : null"
                        :style="[
                          isButtonDisabled2
                            ? { cursor: 'not-allowed' }
                            : { cursor: 'pointer' }
                        ]"
                      ><i class="fa fa-repeat mr-1" aria-hidden="true"></i>Make Expired
                        <img
                          src="@/assets/img/git_loader.gif"
                          style="display:none"
                          width="25px"
                          class="ml-3 loader2"
                        />
                      </button>
                    </div>
                </div>
                <div class="mt-3" v-show="unUsed">
                  <button class="btn btn-info" @click="unUseVoucher"
                        :disabled="isButtonDisabled2 ? true : null"
                        :style="[
                          isButtonDisabled2
                            ? { cursor: 'not-allowed' }
                            : { cursor: 'pointer' }
                        ]"
                      ><i class="fa fa-repeat mr-1" aria-hidden="true"></i>Un-Use
                        <img
                          src="@/assets/img/git_loader.gif"
                          style="display:none"
                          width="25px"
                          class="ml-3 loader2"
                        />
                      </button>
                </div>
        </div>
      </div>
  </masterLayout>
</template>

<script>
import Vue from "vue";
import masterLayout from "@/views/dashboard/masterLayout";
import backImg from "@/assets/img/pattern_img.png";
import configObject from "@/config";
import Jquery from "jquery";
let $ = Jquery;

export default {
  components: {
    masterLayout,
  },
  data() {
    return {
      backImg,
      voucherPin: null,
      isButtonDisabled: false,
      voucherVerified: false,
      voucherDetails: {},
      isButtonDisabled: false,
      isButtonDisabled2: false,
      showExtras: false,
      usedVoucher: false,
      unUsed: false,
      showExpiry: false
    };
  },
  methods: {
    verifyVoucher(event) {
      event.preventDefault();
      if (!this.voucherPin) {
        this.$toast("Please input a voucher pin", {
          type: "error",
          timeout: 3000,
        });
        return;
      }

      $(".loader").show();
      this.isButtonDisabled = true;

      this.axios
        .post(
          `${
            configObject.apiBaseUrl
          }/Admin/VoucherMonitor?pin=${this.voucherPin.toString()}`,
          {},
          configObject.authConfig()
        )
        .then((res) => {
          console.log(res.data)
          if (res.data.deleted == true || res.data.isUsed == true) {
            this.showExtras = false
          } else {
            this.showExtras = true
            this.$toast("Successfully verified voucher", {
              type: "success",
              timeout: 3000,
            });
          }
          if (res.data.isUsed == true) {
            this.usedVoucher = true
            this.unUsed = false
            if (!res.data.amountSpent) {
              this.unUsed = true
            }
            if (!res.data.branchName) {
              this.unUsed = true
            }
            if (!res.data.transactionDate) {
              this.unUsed = true
            }
          } else {
            this.usedVoucher = false
            this.unUsed = false
          }
          if (res.data.transactionDate) {
            res.data.transactionDate = this.$moment(res.data.transactionDate).format('DD/MM/YYYY HH:mm:ss')
          }
          if (res.data.amountSpent) {
            res.data.amountSpent = this.convertThousand(res.data.amountSpent)
          }
          if (res.data.expiry) {
            this.showExpiry = true
            res.data.expiry = this.$moment(res.data.expiry).format('DD/MM/YYYY HH:mm:ss')
          } else {
            this.showExpiry = false
          }
          const data = { ...res.data, amount: this.convertThousand(res.data.amount), dateGenerated: this.$moment(res.data.dateGenerated).format("DD/MM/YYYY hh:mm A"), isUsed: res.data.isUsed == true ? 'Yes': 'No', deleted: res.data.deleted == true ? 'Yes' : 'No' }
          this.voucherPin = null
          this.voucherDetails = data
          this.voucherVerified = true
          this.isButtonDisabled = false;
          $(".loader").hide();
        })
        .catch((error) => {
          this.isButtonDisabled = false;
          $(".loader").hide();
          this.$toast(error.response.data.message, {
            type: "error",
            timeout: 3000,
          });
        });
    },
    cancelVoucher() {
      $('.loader').show();
      this.isButtonDisabled = true;

      this.axios.post(`${configObject.apiBaseUrl}/Admin/CancelVoucher?id=${this.voucherDetails.id}`, {}, configObject.authConfig())
          .then(res => {
                this.$toast("Successfully Cancelled Voucher", {
                    type: "success",
                    timeout: 3000
                });
                this.isButtonDisabled = false;
                $('.loader').hide();
          })
          .catch(error => {
              this.isButtonDisabled = false;
              $('.loader').hide();
              this.$toast(error.response.data.message, {
                  type: "error",
                  timeout: 3000
              });
          });
    },
    unUseVoucher() {
      $('.loader').show();
      this.isButtonDisabled = true;

      this.axios.post(`${configObject.apiBaseUrl}/Admin/MakeVoucherAvailable?id=${this.voucherDetails.id}`, {}, configObject.authConfig())
          .then(res => {
                this.$toast("Successfully Un-Used Voucher", {
                    type: "success",
                    timeout: 3000
                });
                this.isButtonDisabled = false;
                $('.loader').hide();
                this.voucherVerified = false
                this.voucherPin = null
          })
          .catch(error => {
            console.log(error)
            console.log(error.resposne)
              this.isButtonDisabled = false;
              $('.loader').hide();
              this.$toast(error.response.data.message, {
                  type: "error",
                  timeout: 3000
              });
          });
    },
    expireVoucher() {
      $('.loader2').show();
      this.isButtonDisabled2 = true;

      this.axios.post(`${configObject.apiBaseUrl}/Admin/MakeVoucherExpired?id=${this.voucherDetails.id}`, {}, configObject.authConfig())
          .then(res => {
                this.$toast("Successfully Cancelled Voucher", {
                    type: "success",
                    timeout: 3000
                });
                this.isButtonDisabled2 = false;
                $('.loader2').hide();
          })
          .catch(error => {
              this.isButtonDisabled2 = false;
              $('.loader2').hide();
              this.$toast(error.response.data.message, {
                  type: "error",
                  timeout: 3000
              });
          });
    },
    convertThousand(request) {
        if (!isFinite(request)) {
            return "0.00";
        }
        return request.toFixed(2).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    },
  },
};
</script>